Flutter communicate engines
genexus-books/gx-super-app pull request #63
Opened 2024-09-24 14:43 UTC by ebazterrica

Android: get Session information of Super App in PlaymentConfirm screen.

Pending iOS

2024-09-24 16:20 UTC, jotapeg requested changes
No entendí el flujo... ¿La parte Flutter invoca a getSessionInformation que a través del method channel invoca a la parte Kotlin que a su vez a través del method channel invoca a la parte Flutter de nuevo para que le retorne el token JWT? ¿Por qué no directamente hacer Flutter-Flutter y evitar la pasarela por Kotlin que parece innecesaria?

2024-09-24 18:07 UTC, ebazterrica commented on .DS_Store
Ahí lo agregué para excluirlo, pero como lo puedo borrar del commit?

Respecto al flujo, tiene que ser así porque la pantalla de confirmación está en un Engine2 y no puede comunicarse con el Engine1 en donde está la Super App.

![image](https://github.com/user-attachments/assets/32cebf9f-7bf0-4449-86d6-803b0dee3d75)

2024-09-24 18:09 UTC, ebazterrica commented
Respecto al flujo, tiene que ser así porque la pantalla de confirmación está en un Engine2 y no puede comunicarse con el Engine1 en donde está la Super App.

Esto me paso el experto de Flutter:
![image](https://github.com/user-attachments/assets/32cebf9f-7bf0-4449-86d6-803b0dee3d75)

2024-09-24 19:22 UTC, jotapeg approved these changes
Ok Android entonces si hay una restricción de la plataforma para hacerlo así

2024-09-25 08:39 UTC, finthamoussu requested changes

2024-09-25 08:39 UTC, finthamoussu commented on Flutter/example_superapp/example/ios/Runner/FlutterPaymentViewController.swift
> +                let errDesc = "Invalid result arguments: \(String(describing: call.arguments))"
`result` is not called here. Also `errDesc` is not used.

2024-09-25 08:52 UTC, finthamoussu commented on Flutter/example_superapp/example/ios/Runner/FlutterPaymentViewController.swift
> +                let errDesc = "Invalid result arguments: \(String(describing: call.arguments))"
Fixed in https://github.com/genexus-books/gx-super-app/pull/63/commits/5eeec1208fa95fbf67a8bcd3c7808b20c2e66cb0

2024-09-25 08:52 UTC, finthamoussu commented on Flutter/example_superapp/example/ios/Runner/FlutterPaymentViewController.swift
> +	}
Fixed in https://github.com/genexus-books/gx-super-app/pull/63/commits/5eeec1208fa95fbf67a8bcd3c7808b20c2e66cb0

2024-09-25 08:53 UTC, finthamoussu approved these changes
Previous concerns were fixed in https://github.com/genexus-books/gx-super-app/pull/63/commits/5eeec1208fa95fbf67a8bcd3c7808b20c2e66cb0

2024-09-25 13:19 UTC, merged