GX Render - React Native iOS example
genexus-books/gx-super-app pull request #9
Opened 2023-06-22 17:16 UTC by CinthyaRiverosGlb

# SuperApp Example
This document explains how to develop and integrate the functionality that provides the API for access to the Mini Apps Center, as well as the API for managing their cache, based on the MiniAppCaller example.

## How to run the react native example

Install the node modules and pods folders on the root folder ExampleSuperApp

npm install && cd ios && pod install && pod update && cd ..

To run de metro (react native server)
 
npx react-native start

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒

                Welcome to Metro v0.73.9
              Fast - Scalable - Integrated

r - reload the app
d - open developer menu
i - run on iOS
a - run on Android

_note: if your environment needs extra configuration please follow the official documentation for React Native: https://reactnative.dev/docs/environment-setup_

## Execute ios project 
Open ExampleSuperApp/ios/ExampleSuperApp.xcworkspace or select the option i - run on iOS from Metro

2023-06-27 14:40 UTC, jotapeg submitted a review, later dismissed

2023-06-27 14:40 UTC, jotapeg commented on Android/MiniAppCaller/app/src/main/java/com/genexus/superapps/bankx/ui/screens/main/MiniAppListHomeContent.kt
> +        if (BuildConfig.FLAVOR == Flavor.SANDBOX && Services.SuperApps.isSandboxEnvironment()) {
Este es uno de los cambios que no puede bajar

2023-06-27 14:40 UTC, jotapeg commented on Android/MiniAppCaller/app/src/main/java/com/genexus/superapps/bankx/viewmodel/main/MainViewModel.kt
> +        val task = Services.SuperApps.loadSandbox()
Este es otro que tampoco puede bajar

2023-06-27 14:40 UTC, jotapeg commented on Android/MiniAppCaller/build.gradle
> +        fc_version = "1.6-SNAPSHOT"
Y este es otro que tampoco baja

2023-06-27 14:40 UTC, jotapeg commented on Android/Logging.md
> -```
¿Por qué se borró esto?

2023-06-27 14:41 UTC, jotapeg commented on CreateSuperApp.md
> +4. Provide the communication interface in the Super App, which will be called from the integrated Mini Apps
Este archivo tampoco entendí por qué cambió y se borró lo de sandbox al final

2023-07-31 07:35 UTC, finthamoussu requested changes

2023-07-31 07:35 UTC, finthamoussu commented on ReactNative/ExampleSuperApp/ios/ExampleSuperApp.xcodeproj/project.pbxproj
> +		C9E7479B2A35504500D3F898 /* GXFoundation.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = GXFoundation.framework; path = "../../../../../Library/Developer/Xcode
These relative paths are not correct. Should point to [iOS/GeneXus Frameworks](https://github.com/genexus-books/gx-super-app/tree/main/iOS/GeneXus%20Frameworks)

2023-07-31 07:35 UTC, finthamoussu commented on ReactNative/ExampleSuperApp/ios/GeneXus Frameworks/README.md
> +
This folder is not needed, point to [iOS/GeneXus Frameworks](https://github.com/genexus-books/gx-super-app/tree/main/iOS/GeneXus%20Frameworks)

2023-09-08 08:18 UTC, finthamoussu approved these changes
Updated dependencies to use SPM, the rest LGTM.

2023-09-08 08:21 UTC, merged